# report_section_order:
#   software_versions:
#     order: -1000
#   "pipelines-technology-nanopore_demux-summary":
#     order: -1001

# export_plots: true

run_modules:
  - custom_content
  - fastqc
  - samtools

module_order:
  - fastqc
  - samtools:
    name: "Host Genome"
    info: "Host genonme alignment information"
    path_filters:
      - "*/*.host.stats"
      - "*/*.host.idxstats"
      - "*/*.host.flagstat"
  - custom_content
