# report_section_order:
#   software_versions:
#     order: -1000
#   "pipelines-technology-nanopore_demux-summary":
#     order: -1001

# export_plots: true

run_modules:
  - custom_content
  - fastqc

module_order:
  - fastqc
  - custom_content
