title: "Viral Genomics"
subtitle: "Viral Genomics Pipeline Report"
intro_text: ""

# report_section_order:
#   software_versions:
#     order: -1000
#   "pipelines-technology-nanopore_demux-summary":
#     order: -1001

show_analysis_paths: false
show_analysis_time: false
export_plots: true
disable_version_detection: true
sample_names_replace_exact: true

run_modules:
  - custom_content
  - fastqc
  - fastp
  - samtools

module_order:
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "*raw*fastqc.zip"
  - fastp
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "FastQC results after adapter trimming."
      target: ""
      path_filters:
        - "*trimmed*fastqc.zip"
  - samtools:
      name: "Host Genome Alignment Stats"
      anchor: "samtools_host"
      info: ""
      path_filters:
        - "*host*"
  - samtools:
      name: "Viral Genome Alignment Stats"
      anchor: "samtools_viral"
      info: ""
      path_filters:
        - "*viral*"
  - custom_content

remove_sections:
  - fastqc_raw_fastqc_status_checks
  - fastqc_trimmed_fastqc_status_checks
  - samtools_host_samtools-idxstats

fn_clean_trim:
  - ".host"
  - ".host.stats"
  - ".viral"
  - ".viral.stats"

extra_fn_clean_exts:
  - "_trimmed_1"
  - "_trimmed_2"
  - "_raw_1"
  - "_raw_2"
