title: "Viral Genomics"
subtitle: "Viral Genomics Pipeline Report"
intro_text: ""

# report_section_order:
#   software_versions:
#     order: -1000
#   "pipelines-technology-nanopore_demux-summary":
#     order: -1001

show_analysis_paths: false
show_analysis_time: false
export_plots: true
disable_version_detection: true
sample_names_replace_exact: true

run_modules:
  - custom_content
  - fastqc
  - fastp
  - samtools

module_order:
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "*raw*fastqc.zip"
  - fastp
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "FastQC results after adapter trimming."
      target: ""
      path_filters:
        - "*trimmed*fastqc.zip"
  - samtools:
      name: "Host Genome Alignment Stats"
      anchor: "samtools_host"
      info: "Host genome alignment stats"
      path_filters:
        - "*host*"
  - custom_content

remove_sections:
  - fastqc_raw_fastqc_status_checks
  - fastqc_trimmed_fastqc_status_checks
  - samtools_host_samtools-idxstats








# report_section_order:
#   software_versions:
#     order: -1000
#   "pipelines-technology-nanopore_demux-summary":
#     order: -1001

# export_plots: true

# run_modules:
#   - custom_content
#   - fastqc
#   - samtools

# module_order:
#   - fastqc
#   - samtools:
#     name: "Host Genome"
#     info: "Host genonme alignment information"
#     path_filters:
#       - "*/*.host.stats"
#       - "*/*.host.idxstats"
#       - "*/*.host.flagstat"
#   - custom_content
