title: "Viral Genomics"
subtitle: "Viral Genomics Pipeline Report"
intro_text: ""

# report_section_order:
#   software_versions:
#     order: -1000
#   "pipelines-technology-nanopore_demux-summary":
#     order: -1001

show_analysis_paths: false
show_analysis_time: false
export_plots: true
disable_version_detection: true
sample_names_replace_exact: true

run_modules:
  - custom_content
  - fastqc
  - fastp
  - samtools
  - picard
  - mosdepth
  - quast
  - snpeff
  - nextclade
  - pangolin

module_order:
  - pangolin:
      name: "VARIANTS: Pangolin"
      info: "This section of the report shows Pangolin lineage analysis results for the called variants."
      path_filters:
        - "*.pangolin.csv"
  - fastqc:
      name: "READ QC: FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "*raw*fastqc.zip"
  - fastp
  - fastqc:
      name: "READ QC: FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "FastQC results after adapter trimming."
      target: ""
      path_filters:
        - "*trimmed*fastqc.zip"
  - samtools:
      name: "ALINGMENT: Host Genome Alignment Stats"
      anchor: "samtools_host"
      info: ""
      path_filters:
        - "*host*"
  - samtools:
      name: "ALINGMENT: Contaminent Genome Alignment Stats"
      anchor: "samtools_contaminent"
      info: ""
      path_filters:
        - "*contam*"
  - samtools:
      name: "ALINGMENT: Viral Genome Alignment Stats"
      anchor: "samtools_viral"
      info: ""
      path_filters:
        - "*viral*"
  - picard:
      name: "ALIGNMENT: Duplicates"
      anchor: "picard_dups"
      info: ""
  - mosdepth:
      name: "ALIGNMENT: Genome Depth"
      anchor: "mosdepth"
      info: ""
  - quast:
      name: "VARIANTS: QUAST"
      anchor: "quast_consensus"
      info: "This section of the report shows QUAST QC results for the consensus sequence."
      path_filters:
        - "*.tsv"
  - snpeff:
      anchor: "snpeff_ann"
      name: "VARIANTS: Snpeff Annotation"
      info: ""
  - custom_content

remove_sections:
  - fastqc_raw_fastqc_status_checks
  - fastqc_trimmed_fastqc_status_checks
  - samtools_host_samtools-idxstats

fn_clean_trim:
  - ".host"
  - ".host.stats"
  - ".contam"
  - ".contam.stats"
  - ".viral"
  - ".viral.stats"

extra_fn_clean_exts:
  - "_trimmed_1"
  - "_trimmed_2"
  - "_raw_1"
  - "_raw_2"
  - "_final"
